Allow to set replica configuration on aws_dynamodb_table resource
cloudposse/terraform-aws-dynamodb pull request #66
Opened 2020-09-04 14:05 UTC by KnupMan

## what
* This feature will allow setting `replica` configurations for `aws_dynamodb_table` resource.

## why
* According to the note at [AWS provider v3.4.0 docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_global_table), it's recommended to use `replica` configuration instead of `aws_dynamodb_global_table` resource and there is a lack of that functionality in this module.

## references
* Closes https://github.com/cloudposse/terraform-aws-dynamodb/issues/41

2020-09-07 12:07 UTC, KnupMan commented
@nitrocode @brcnblc can you please look at this?

2020-09-07 14:34 UTC, vladgolubev approved these changes
Thanks for making this change 👍

2020-10-09 16:15 UTC, SweetOps requested changes

2020-10-09 16:15 UTC, SweetOps commented on variables.tf
> +}
```suggestion
variable "replicas" {
  type = list(string)
  default     = null
  description = "List of regions to create replica"
}
```

2020-10-09 16:15 UTC, SweetOps commented on main.tf
> +
```suggestion
  dynamic "replica" {
    for_each = var.replicas
    content {
      region_name = replica.value
    }
  }

```

2020-10-19 16:09 UTC, czerasz commented
Should there also be?

```diff
--- a/main.tf
+++ b/main.tf
@@ -63,7 +63,8 @@ resource "aws_dynamodb_table" "default" {
   hash_key         = var.hash_key
   range_key        = var.range_key
   stream_enabled   = var.enable_streams
-  stream_view_type = var.enable_streams ? var.stream_view_type : ""
+  stream_enabled   = length(var.replicas) > 0 ? true : var.stream_enabled
+  stream_view_type = length(var.replicas) > 0 || var.enable_streams ? var.stream_view_type : ""
 
   server_side_encryption {
     enabled = var.enable_encryption
```

2021-03-08 11:04 UTC, jacoor commented
@KnupMan is there a possibility of fixing the conflict?

2021-04-30 14:06 UTC, SweetOps commented
closed in favour https://github.com/cloudposse/terraform-aws-dynamodb/pull/83

2021-04-30 14:06 UTC, closed without merging